--liquibase formatted sql

--changeset moin.choudhury:1
--comment: Create Authors table
CREATE TABLE authors (
    author_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(150),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
--rollback DROP TABLE authors;

--changeset moin.choudhury:2
--comment: Create Royalties table
CREATE TABLE royalties (
    royalty_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id NUMBER NOT NULL,
    title_name VARCHAR2(255) NOT NULL,
    royalty_amount DECIMAL(10, 2) NOT NULL,
    currency VARCHAR2(3) DEFAULT 'EUR',
    payment_status VARCHAR2(20) DEFAULT 'PENDING',
    processed_date DATE,
    CONSTRAINT fk_author FOREIGN KEY (author_id) REFERENCES authors(author_id)
);
--rollback DROP TABLE royalties;

--changeset moin.choudhury:3
--comment: Insert Mock Data
INSERT INTO authors (first_name, last_name, email) VALUES ('Thomas', 'Mann', 'thomas.mann@publishing.de');
INSERT INTO royalties (author_id, title_name, royalty_amount, payment_status) VALUES (1, 'Buddenbrooks', 5000.00, 'PAID');
INSERT INTO royalties (author_id, title_name, royalty_amount, payment_status) VALUES (1, 'The Magic Mountain', 3200.50, 'PENDING');

--changeset moin.choudhury:4
--comment: Add Compliance Column (GDPR)
ALTER TABLE authors ADD (gdpr_consent_status VARCHAR2(20) DEFAULT 'UNKNOWN');
--rollback ALTER TABLE authors DROP COLUMN gdpr_consent_status;

--changeset moin.choudhury:5
--comment: Insert New Royalty Entry for Metamorphosis
INSERT INTO royalties (author_id, title_name, royalty_amount, payment_status) VALUES (1, 'The Metamorphosis', 1250.75, 'APPROVED');
--rollback DELETE FROM royalties WHERE title_name = 'The Metamorphosis';

--changeset moin.choudhury:6
--comment: Insert new data in the authors table
INSERT INTO authors (first_name, last_name, email) VALUES ('Benn', 'Duckket', 'Benn.Duckket@publishing.de');
--rollback DELETE FROM authors WHERE first_name = 'Benn';