---
- name: Deploy Klopotek Demo Stack
  hosts: local
  gather_facts: true

  # 1. REMOVED 'vars_files' (Secrets now come from Env)

  vars:
    deploy_dir: "/home/{{ ansible_user_id }}/klopotek_deployment"
    source_dir: "."
    # 2. READ SECRETS FROM ENV (Injected by GitHub)
    oracle_password: "{{ lookup('env', 'ORACLE_PASSWORD') }}"
    app_user: "{{ lookup('env', 'APP_USER') }}"
    app_user_password: "{{ lookup('env', 'APP_USER_PASSWORD') }}"

  tasks:
    - name: Ensure deployment directory exists
      ansible.builtin.file:
        path: "{{ deploy_dir }}"
        state: directory
        mode: '0755'

    - name: Copy Infrastructure files to deployment directory
      ansible.builtin.copy:
        src: "{{ source_dir }}/{{ item }}"
        dest: "{{ deploy_dir }}/"
        mode: '0644'
      loop:
        - docker-compose.yml
        - dockerfile
        - changelog.sql
        - prometheus.yml

    - name: Tear down existing services (Ensure clean state)
      community.docker.docker_compose_v2:
        project_src: "{{ deploy_dir }}"
        state: absent
        remove_orphans: true
      failed_when: false

    - name: Pull latest images
      community.docker.docker_image:
        name: "{{ item }}"
        source: pull
      loop:
        - gvenzl/oracle-xe:21-slim-faststart
        - iamseth/oracledb_exporter:latest
        - prom/prometheus:latest
        - grafana/grafana:latest

    - name: Deploy Stack via Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ deploy_dir }}"
        state: present
        build: always
      register: deployment_output
      # 3. PASS ANSIBLE VARIABLES (FROM ENV) TO DOCKER
      environment:
        ORACLE_PASSWORD: "{{ oracle_password }}"
        APP_USER: "{{ app_user }}"
        APP_USER_PASSWORD: "{{ app_user_password }}"

    - name: Show Deployment Status
      ansible.builtin.debug:
        msg: "Deployment finished! Services: {{ deployment_output.services | default('No changes') }}"

    - name: Wait for Liquibase to complete migration
      ansible.builtin.command: docker wait klopotek-deployment-manager
      register: migration_result
      changed_when: false

