---
- name: Deploy Klopotek Demo Stack
  hosts: local
  gather_facts: yes

  # FIX 1: You MUST include this to load the variables!
  vars_files:
    - secrets.yml

  vars:
    deploy_dir: "/home/{{ ansible_user_id }}/klopotek_deployment"
    source_dir: "."

  tasks:
    - name: Ensure deployment directory exists
      file:
        path: "{{ deploy_dir }}"
        state: directory
        mode: '0755'

    - name: Copy Infrastructure files to deployment directory
      copy:
        src: "{{ source_dir }}/{{ item }}"
        dest: "{{ deploy_dir }}/"
        mode: '0644'
      loop:
        - docker-compose.yml
        - Dockerfile
        - changelog.sql
        - prometheus.yml

    - name: Tear down existing services (Ensure clean state)
      community.docker.docker_compose_v2:
        project_src: "{{ deploy_dir }}"
        state: absent
        remove_orphans: true
      ignore_errors: yes

    - name: Pull latest images
      community.docker.docker_image:
        name: "{{ item }}"
        source: pull
      loop:
        - gvenzl/oracle-xe:21-slim-faststart
        - iamseth/oracledb_exporter:latest
        - prom/prometheus:latest
        - grafana/grafana:latest

    - name: Deploy Stack via Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ deploy_dir }}"
        state: present
        build: always
      register: deployment_output
      # This puts the variables into the shell environment so Docker Compose can see them
      environment:
        ORACLE_PASSWORD: "{{ vault_oracle_password }}"
        APP_USER: "{{ vault_db_user }}"
        APP_USER_PASSWORD: "{{ vault_db_pass }}"

    - name: Wait for Liquibase to complete migration
      command: docker wait klopotek-deployment-manager
      register: migration_result
      changed_when: false

    - name: Verify Database Data (With Formatting)
      # FIX 2: Use the variables here too! Don't hardcode 'stream_user/stream_pass'
      shell: >
        docker exec klopotek-oracle sh -c "echo 'SET PAGESIZE 50000 LINESIZE 300 TRIMSPOOL ON FEEDBACK OFF HEADING ON; COLUMN title_name FORMAT a30; COLUMN payment_status FORMAT a20; SELECT * FROM royalties;' | sqlplus -S {{ vault_db_user }}/{{ vault_db_pass }}@//localhost:1521/XEPDB1"
      register: oracle_data
      changed_when: false

    - name: Display Royalties Table
      debug:
        msg: "{{ oracle_data.stdout_lines }}"